[package]
name = "loaf-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
pest = "2.7.15"
pest_derive = "2.7.15"
wasmtime = "27.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
